/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "var(--color-on-error)",
        "on-background": "var(--color-on-background)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary": "var(--color-tertiary)",
        "surface-container": "var(--color-surface-container)",
        "secondary": "var(--color-secondary)",
        "outline-variant": "var(--color-outline-variant)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-dim": "var(--color-surface-dim)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-tint": "var(--color-surface-tint)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-error-container": "var(--color-on-error-container)",
        "on-secondary": "var(--color-on-secondary)",
        "outline": "var(--color-outline)",
        "primary": "var(--color-primary)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface-variant": "var(--color-surface-variant)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface": "var(--color-surface)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-surface": "var(--color-on-surface)",
        "secondary-container": "var(--color-secondary-container)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "surface-bright": "var(--color-surface-bright)",
        "error-container": "var(--color-error-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "background": "var(--color-background)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "error": "var(--color-error)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "primary-container": "var(--color-primary-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-primary": "var(--color-on-primary)"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "2xl": "64px",
        "md": "16px",
        "container_max": "1160px",
        "xl": "40px",
        "sm": "8px",
        "xs": "4px",
        "lg": "24px"
      },
      fontFamily: {
        "body-lg": ["DM Sans", "sans-serif"],
        "body-sm": ["DM Sans", "sans-serif"],
        "headline-xl-mobile": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "headline-xl": ["Sora", "sans-serif"],
        "display-lg": ["Sora", "sans-serif"],
        "label-md": ["DM Sans", "sans-serif"],
        "display-2xl": ["Sora", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-xl-mobile": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "headline-md": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-xl": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-md": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "display-2xl": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0,0,0.2,1) infinite',
      }
    },
  },
  plugins: [],
}
